

#ifndef MAIN_DIMENSIONS_HEADER
#define MAIN_DIMENSIONS_HEADER


    #define HAUTEUR_FENETRE 600
    #define LARGEUR_FENETRE 500
    #define HAUTEUR_SPAWN -50

    #define TIME_BEFORE_RESPAWN 1.5f
    #define NUMBER_OF_LIVES 4


#endif
