

#ifndef MAIN_DIMENSIONS_HEADER
#define MAIN_DIMENSIONS_HEADER


    #define HAUTEUR_FENETRE 700
    #define HAUTEUR_HUD 75
    #define LARGEUR_FENETRE 600
    #define HAUTEUR_SPAWN -50

    #define TIME_BEFORE_RESPAWN 1.5f

    #define GAP_BETWEEN_LIFE_INDICATORS 100
    #define FIRST_LIFE_INDICATOR_POSITION sf::Vector2f(30, HAUTEUR_HUD / 2 - 20)
    #define SECOND_LIFE_INDICATOR_POSITION FIRST_LIFE_INDICATOR_POSITION + sf::Vector2f(GAP_BETWEEN_LIFE_INDICATORS, 0)
    #define THIRD_LIFE_INDICATOR_POSITION SECOND_LIFE_INDICATOR_POSITION + sf::Vector2f(GAP_BETWEEN_LIFE_INDICATORS, 0)

    #define SCORE_POSITION sf::Vector2f(LARGEUR_FENETRE - 10, HAUTEUR_HUD / 2 - 10)


#endif
